name: End-to-end tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Baixando o projeto
        uses: actions/checkout@v4
      
      - name: Executando testes Cypress
        uses: cypress-io/github-action@v6
