name: End-to-end tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Baixando o projeto
        uses: actions/checkout@v4
      
      - name: Executando testes Cypress
        uses: cypress-io/github-action@v6
 
      - name: Subindo relatórios de teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports-html
          path: cypress/reports/html